# Generated by Django 6.1 on 2026-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('table_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
