# Generated by Django 6.1 on 2026-09-09 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_table'),
        ('orders', '0004_order_full_name_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='booking.booking'),
        ),
    ]
